language: java
jdk:
  - oraclejdk8
before_install:
  - npm install bower -g
  - bower install
script: mvn clean install
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer